"""
State constants for the BoxBot Telegram bot.
These states help track user conversation state in the bot.
"""

# Main states
IDLE = "IDLE"
AWAITING_STORAGE_NAME = "AWAITING_STORAGE_NAME"
AWAITING_STORAGE_PHOTO = "AWAITING_STORAGE_PHOTO"
AWAITING_EDIT_STORAGE = "AWAITING_EDIT_STORAGE"
AWAITING_ITEMS_LIST = "AWAITING_ITEMS_LIST"
AWAITING_ITEM_EDIT = "AWAITING_ITEM_EDIT"
AWAITING_ITEM_PHOTO = "AWAITING_ITEM_PHOTO"
AWAITING_ITEM_DELETE_CONFIRM = "AWAITING_ITEM_DELETE_CONFIRM"
AWAITING_ITEM_MOVE = "AWAITING_ITEM_MOVE"
AWAITING_STORAGE_DELETE_CONFIRM = "AWAITING_STORAGE_DELETE_CONFIRM"
AWAITING_TRASH_CLEAR_CONFIRM = "AWAITING_TRASH_CLEAR_CONFIRM"
SEARCHING = "SEARCHING"

# Context keys
STORAGE_ID = "storage_id"
ITEM_NAME = "item_name"
EDIT_FIELD = "edit_field"
CURRENT_PAGE = "current_page"
LAST_STORAGE_PAGE = "last_storage_page"
LAST_ITEM_PAGE = "last_item_page"
LOCATION_ID = "location_id"
SEARCH_TYPE = "search_type"  # "storage", "item", or "both"

# Search types
SEARCH_STORAGE = "storage"
SEARCH_ITEM = "item"
SEARCH_BOTH = "both" 